apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: video-worker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: video-worker
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      describedObject:
        kind: Service
        name: video-worker-exporter-service
      metric:
        name: celery_queue_length
      target:
        type: Value
        value: 20
  behavior:
    scaleDown:
      # Wait for 5 minutes of consistent low load before scaling down
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      # Use 'Min' to pick the policy that removes the fewest pods
      selectPolicy: Min